---
exclude: ^(\.[^/]*cache/.*)$
repos:
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '75', --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-beautysh
          # -mdformat-shfmt
          # -mdformat-tables
          - mdformat-config
          #- mdformat-black
          - mdformat-web
          - mdformat-gfm
          - setuptools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      # - id: check-toml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.34.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - '{extends: relaxed, rules: {line-length: {max: 90}}}'
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          - -i
          - "2"
        additional_dependencies:
          - setuptools
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          # - --builtin=clear,rare,informal,usage,code,names,en-GB_to_en-US
          - --builtin=clear,rare,informal,usage,code,names
          - --ignore-words-list=hass,master
          - --skip="./.*"
          - --quiet-level=2
